[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xf4a261"
index = 16

[[colors.indexed_colors]]
color = "0xd67ad2"
index = 17

[colors.bright]
black = "0x475072"
blue = "0x84cee4"
cyan = "0x59f0ff"
green = "0x58cd8b"
magenta = "0xb8a1e3"
red = "0xd6616b"
white = "0xf2f2f2"
yellow = "0xffe37e"

[colors.normal]
black = "0x393b44"
blue = "0x719cd6"
cyan = "0x63cdcf"
green = "0x81b29a"
magenta = "0x9d79d6"
red = "0xc94f6d"
white = "0xdfdfe0"
yellow = "0xdbc074"

[colors.primary]
background = "0x192330"
foreground = "0xcdcecf"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "MesloLGMDZ Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGMDZ Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGMDZ Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true


[scrolling]
history = 0
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[terminal.shell]
args = ["--login"]
program = "/opt/homebrew/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 4
y = 3

[general]
live_config_reload = true
working_directory = "None"

[terminal]
